@startuml

skinparam monochrome true
skinparam componentStyle uml2

package "Sabi Webclient" {
HTTP - [JSF-WebApp]
database Prometheus
[grafana] -> Prometheus
}

package "Sabi Backend" {
title Level 1 view
interface "SABI REST API" as rest
database db
[JSF-WebApp] ..> rest : use
[REST Facade] - rest
[Services] <- [REST Facade]
[Repository] --> db

together {
[Services] --> [Repository]
[Reporting] --> [Repository]
[BI Scheduler] --> [Repository]
}

[Services] --> [Hazelcast\nCache]

interface "CAPTCHA REST API" as rest2
rest2 - [Captcha]


[Services] ..> rest2 : use
rest2 <.. [HTML5-WebApp] : use

}

package "Supporting Cloud Services" {

interface smtp
smtp - [Mailer]
[Services] ..> smtp : use

}

@enduml