# Will be deployed aside of the jar, to set the memory options
# as the spring-boot-maven-plugin ignores the jvmArguments Option
# Java 22
export JAVA_OPTS="-Djava.io.tmpdir=/var/captcha/tmp -XX:-UsePerfData -Xmx81m -Xms64m -XX:MaxMetaspaceSize=128m"
