@startuml

skinparam monochrome true
skinparam componentStyle uml2

title Targeted Low-Budget Deployment for the Beginning

cloud "Internet" {

 node "DynDNS" {
 }
 note right of DynDNS : Uses DnyDNS Service of my provider,\n to make the WebApp on PIs at\n homebased LAN available to the public

 node "Sabi Users PC" {
   [WebBrowser]
 }

 node "Mailservice" {
    interface smtp
    [SMTP] - smtp
 }

}

cloud "Home LAN" {


  node "RaspberryPi-2" {

      package "SpringBootApp Captcha" {
          interface "CAPTCHA\nREST API" as rest2
          rest2 - [CAPTCHA]
      }

      package "SpringBootApp Sabi-BE" {
         interface "SABI\nREST API" as rest
         rest - [REST Facade]
         [REST Facade] -> [Services]
         [Services] -> [Repository]
         [Services] .u.>smtp : smtp
         [Services] ..>rest2 : https
      }

  }

  node "RaspberryPi-1" {
    package "Tomcat FE" {
      HTTP - [WebApp]
      [WebApp] ..> rest : https
      [WebApp] ..> rest2 : https
    }
  }

node "RaspberryPi-3" {
     database "MySQL" as db {
        folder "SabiDB" {
          interface SQL
          [sabi-prod-db] - SQL
          [sabi-stage-db]
        }
}

' Relelationships
[WebBrowser] ..> HTTP : use
[Repository] --> SQL : jdbc


@enduml