@startuml

title Distribution of rough components


 package "Tomcat FE" {
   [Sabi WebApp] ..> [Tomcat BE] : uses
 }

   package "Tomcat BE" {
      [Sabi Backend] ..> db : uses
   }

 package "Users PC" {
   [WebBrowser] ..> [Sabi WebApp] : uses
 }

 database "MySQL" as db {
    folder "SabiDB" {
      [sabi-prod-db]
    }
}

@enduml