CREATE TABLE `users` (
  `id`             BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `EMAIL`          VARCHAR(255)        NOT NULL,
  `PASSWORD`       VARCHAR(255)        NOT NULL,
  `CREATED_ON`     TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `VALIDATE_TOKEN` VARCHAR(255)        NOT NULL,
  `VALIDATED`      BOOLEAN                      DEFAULT FALSE,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UNQ_EMAIL` (`EMAIL`)
)
  ENGINE =InnoDB
  AUTO_INCREMENT =100
  DEFAULT CHARSET =utf8


