@startuml

skinparam monochrome true
skinparam componentStyle uml2

actor Aquarist
participant SabiClient
participant CaptchaService
participant SabiService
database SabiDB

group password_forgotten
    Aquarist -> SabiClient: Clicks on\npassword forgotten
    SabiClient -> CaptchaService : getNewChallenge()
    SabiClient -> SabiClient : render password\nforgotten form
    Aquarist -> SabiClient : Fills in email\nand captcha answer
    SabiClient -> SabiService : requestReset\nPasswordEmail(emailadr,captcha token)
    SabiClient -> SabiClient : render enter new\npassword form
    SabiService -> CaptchaService : validate\n Captcha Token
    SabiService -> SabiService : generate and remember\nreset token for user\nfor 10 Minutes
    SabiService -> Aquarist : Sends email with reset token to be used
    Aquarist -> SabiClient : Fills in new password\nand reset token
    SabiClient -> SabiService : resetUsersPassword(emailadr,newPassword,reset token)
    SabiService -> SabiService : validateConstraints
    SabiService -> SabiDB : changePassword
    SabiService -> Aquarist : Sends password changed confirmation email
end

@enduml