@startuml

skinparam monochrome true
skinparam componentStyle uml2

title Targeted Low-Budget Deployment for the Beginning

cloud "Internet" {

 node "Sabi Users PC" {
   interface HTTP
   [WebBrowser] ..> HTTP : use
 }

   node "DynDNS" {
   }
   note bottom of DynDNS : Uses DnyDNS Service of my provider,\n to make the WebApp on PIs at\n homebased LAN available to the public

node "Mailservice" {
interface smtp
[SMTP] - smtp
}

}

cloud "Home LAN" {


  node "RaspberryPi-2" {

      package "SpringBootApp Captcha" {
          interface "CAPTCHA REST API" as rest2
          rest2 - [CAPTCHA]
      }

      package "SpringBootApp Sabi-BE" {
      interface "SABI REST API" as rest
         rest - [REST Facade]
         [REST Facade] -> [Services]
         [Services] -> [Repository]
         [Services] .u.>smtp : smtp
         [Services] ..>rest2 : https
         [Repository] --> db : jdbc
      }

  }

  node "RaspberryPi-1" {
    package "Tomcat FE" {
      HTTP - [WebApp]
      [WebApp] ..> rest : https
      [WebApp] ..> rest2 : https
    }
  }

node "RaspberryPi-3" {
     database "MySQL" as db {
        folder "SabiDB" {
          [sabi-prod-db]
          [sabi-stage-db]
        }

}

@enduml