@startuml

title Targeted Low-Budget Deployment for the Beginning

cloud "Internet" {

 node "Sabi Users PC" {
   [WebBrowser] ..> HTTP : use
 }

   node "Router" {
   }
   note bottom of Router : Uses DnyDNS Service of \n my provider, to make the WebApp \n available to the public

}

cloud "Home LAN" {

  node "RaspberryPi-1" {
    package "Tomcat FE" {
      interface HTTP
      HTTP - [WebApp]
      [WebApp] ..> rest : https
    }
  }

  node "RaspberryPi-2" {
      package "Tomcat BE" {
         interface HTTP_REST as rest
         rest - [REST Facade]
         [REST Facade] -> [Services]
         [Services] -> [Repository]
         [Repository] --> db : jdbc
      }
  }

node "RaspberryPi-3" {
     database "MySQL" as db {
        folder "SabiDB" {
          [sabi-prod-db]
          [sabi-stage-db]
        }

}

@enduml