### Login Request
POST http://{{sabi-host}}:{{sabi-port}}{{sabi-rootctx}}api/auth/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "username": "sabi@bluewhale.de",
  "password": "clibanarius"
}

> {% client.global.set("auth_token", response.headers.valueOf("Authorization")); %}

### Register new User Request
POST http://{{sabi-host}}:{{sabi-port}}{{sabi-rootctx}}api/auth/register
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "captchaCode": "QMhHh",
  "country": "de",
  "email": "schubert@bluewhale.de",
  "language": "de",
  "password": "test",
  "username": "tester"
}

### Get authed users tanks
GET http://{{sabi-host}}:{{sabi-port}}{{sabi-rootctx}}api/tank/list
Authorization: {{auth_token}}
Accept: application/json

### Get known plague status' localized for de
GET http://{{sabi-host}}:{{sabi-port}}{{sabi-rootctx}}api/plagues/status/list/de
Authorization: {{auth_token}}
Accept: application/json

### Get known plague types localized for de
GET http://{{sabi-host}}:{{sabi-port}}{{sabi-rootctx}}api/plagues/type/list/de
Authorization: {{auth_token}}
Accept: application/json

### Register new Plague Record
POST http://{{sabi-host}}:{{sabi-port}}{{sabi-rootctx}}api/plagues/record
Authorization: {{auth_token}}
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

{
  "observedOn" : "2022-10-05T21:29:50.719Z",
  "plagueId" : 4,
  "plagueStatusId" : 5,
  "aquariumId" : 1,
  "plagueIntervallId" : 1
}

### Get users plague records
GET http://{{sabi-host}}:{{sabi-port}}{{sabi-rootctx}}api/plagues/record/list
Authorization: {{auth_token}}
Accept: application/json


### Update User Profile
PUT http://{{sabi-host}}:{{sabi-port}}{{sabi-rootctx}}api/userprofile
Authorization: {{auth_token}}
Accept: application/json
Content-Type: application/json

{
  "country": "DE",
  "language": "de"
}

