/*
 * Copyright (c) 2023 by Stefan Schubert under the MIT License (MIT).
 * See project LICENSE file for the detailed terms and conditions.
 */

package de.bluewhale.sabi.util;

import de.bluewhale.sabi.model.*;
import de.bluewhale.sabi.persistence.model.*;
import jakarta.validation.constraints.NotNull;

import java.util.ArrayList;
import java.util.List;

/**
 * Mapping Util Functions.
 * Since we have very few attributes per class and the targeted runtime environment of a pi at the beginning,
 * I decided to spare the libs for bean mappings like dozer or MapStruts, to gain a slim jar file.
 * Also To2Entity-Direction will ommit the primary key (for security reasons)
 *
 * @author Stefan Schubert
 */
public class Mapper {


    /**
     * Maps given To attributes into provided Entity
     *
     * @param pUserTo
     * @param pUserEntity
     */
    public static void mapUserTo2Entity(@NotNull final UserTo pUserTo, @NotNull final UserEntity pUserEntity) {
        pUserEntity.setId(pUserTo.getId());
        pUserEntity.setEmail(pUserTo.getEmail());
        pUserEntity.setUsername(pUserTo.getUsername());
        // pUserEntity.setPassword(pUserTo.getPassword()); No won't do because of encryption layer
        pUserEntity.setValidated(pUserTo.isValidated());
        pUserEntity.setValidateToken(pUserTo.getValidationToken());
        pUserEntity.setLanguage(pUserTo.getLanguage());
        pUserEntity.setCountry(pUserTo.getCountry());
    }

    /**
     * Maps given Entity attributes into provided To
     *
     * @param pUserEntity
     * @param pUserTo
     */
    public static void mapUserEntity2To(@NotNull final UserEntity pUserEntity, @NotNull final UserTo pUserTo) {
        pUserTo.setId(pUserEntity.getId());
        pUserTo.setEmail(pUserEntity.getEmail());
        pUserTo.setUsername(pUserEntity.getUsername());
        // pUserTo.setPassword(pUserEntity.getPassword()); No won't do because of encryption layer
        pUserTo.setValidated(pUserEntity.isValidated());
        pUserTo.setValidationToken(pUserEntity.getValidateToken());
        pUserTo.setLanguage(pUserEntity.getLanguage());
        pUserTo.setCountry(pUserEntity.getCountry());
    }

    /**
     * Maps given Entity attributes into provided To
     *
     * @param unitEntity
     * @param unitTo
     */
    public static void mapUnitEntity2To(UnitEntity unitEntity, UnitTo unitTo) {
        unitTo.setId(unitEntity.getId());
        unitTo.setDescription(unitEntity.getDescription());
        unitTo.setUnitSign(unitEntity.getName());
    }

    public static void mapUnitToEntity(UnitTo pUnitTo, UnitEntity pUnitEntity) {
        pUnitEntity.setId(pUnitTo.getId());
        pUnitEntity.setDescription(pUnitTo.getDescription());
        pUnitEntity.setName(pUnitTo.getUnitSign());
    }

    public static void mapParameterEntity2To(ParameterEntity parameterEntity, ParameterTo parameterTo) {
        parameterTo.setId(parameterEntity.getId());
        parameterTo.setDescription(parameterEntity.getDescription());
        parameterTo.setBelongingUnitId(parameterEntity.getBelongingUnitId());
        parameterTo.setMinThreshold(parameterEntity.getMinThreshold());
        parameterTo.setMaxThreshold(parameterEntity.getMaxThreshold());
    }

    public static void mapParameterTo2Entity(ParameterTo parameterTo, ParameterEntity parameterEntity) {
        parameterEntity.setId(parameterTo.getId());
        parameterEntity.setDescription(parameterTo.getDescription());
        parameterEntity.setBelongingUnitId(parameterTo.getBelongingUnitId());
        parameterEntity.setMinThreshold(parameterTo.getMinThreshold());
        parameterEntity.setMaxThreshold(parameterTo.getMaxThreshold());        
    }

    public static void mapPlagueRecordEntity2To(PlagueRecordEntity plagueRecordEntity, PlagueRecordTo plagueRecordTo) {
        plagueRecordTo.setPlagueId(plagueRecordEntity.getPlagueId());
        plagueRecordTo.setPlagueStatusId(plagueRecordEntity.getObservedPlagueStatus());
        plagueRecordTo.setAquariumId(plagueRecordEntity.getAquarium().getId());
        plagueRecordTo.setId(plagueRecordEntity.getId());
        plagueRecordTo.setObservedOn(plagueRecordEntity.getObservedOn());
        plagueRecordTo.setPlagueIntervallId(plagueRecordEntity.getPlagueIntervallId());
    }

    public static void mapPlagueRecordTo2Entity(PlagueRecordTo source, PlagueRecordEntity target, AquariumEntity usedTank, UserEntity user) {
        target.setPlagueId(source.getPlagueId());
        target.setObservedPlagueStatus(source.getPlagueStatusId());
        target.setAquarium(usedTank);
        target.setUser(user);
        // target.setId(source.getId()); Autogenerated
        target.setObservedOn(source.getObservedOn());
        target.setPlagueIntervallId(source.getPlagueIntervallId());
    }


    public static void mapUserMeasurementReminderEntity2TO(UserMeasurementReminderEntity source, MeasurementReminderTo target) {
        target.setUserId(source.getUser().getId());
        target.setPastDays(source.getPastdays());
        target.setActive(source.isActive());
        target.setUnitId(source.getUnitId());
    }

    public static void mapUserMeasurementReminderTO2Entity(MeasurementReminderTo source, UserMeasurementReminderEntity target, UserEntity user ) {
        target.setUser(user);
        target.setActive(source.isActive());
        target.setPastdays(source.getPastDays());
        target.setUnitId(source.getUnitId());
    }

    public static List<UnitTo> mapUnitEntities2TOs(@NotNull List<UnitEntity> measurementUnits) {
        List<UnitTo> unitTos = new ArrayList<UnitTo>();
        for (UnitEntity unitEntity : measurementUnits) {
            UnitTo unitTo = new UnitTo();
            Mapper.mapUnitEntity2To(unitEntity, unitTo);
            unitTos.add(unitTo);
        }
        return unitTos;
    }

}
