@startuml

skinparam monochrome true
skinparam componentStyle uml2

package "Sabi GUI" {
HTTP - [HTML5-WebApp]
}

package "Sabi Backend" {
title Level 1 view
interface "SABI REST API" as rest
database db
[HTML5-WebApp] ..> rest : use
rest - [REST Facade]
[REST Facade] -> [Services]
[Repository] --> db

together {
[Services] --> [Repository]
[Reporting] -> [Repository]
[BI Scheduler] -> [Repository]
}

interface "CAPTCHA REST API" as rest2
rest2 - [Captcha]

[Services] ..> rest2 : use
rest2 <.. [HTML5-WebApp] : use

}

@enduml